import { configureStore } from '@reduxjs/toolkit';
import exercisesSlice from './slices/exercisesSlice';

export const store = configureStore({
	reducer: {
		exercises: exercisesSlice,
	},
});

const q = [
	[
		{
			bodyPart: 'waist',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/qC3lqBkzUjNPWM',
			id: '0001',
			instructions: [Array],
			name: '3/4 sit-up',
			secondaryMuscles: [Array],
			target: 'abs',
		},
		{
			bodyPart: 'waist',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/tyDrhGEAcoWKzB',
			id: '0002',
			instructions: [Array],
			name: '45° side bend',
			secondaryMuscles: [Array],
			target: 'abs',
		},
		{
			bodyPart: 'waist',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/iRwXkICfKhopuL',
			id: '0003',
			instructions: [Array],
			name: 'air bike',
			secondaryMuscles: [Array],
			target: 'abs',
		},
		{
			bodyPart: 'upper legs',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/Cb3UiZONv88m1E',
			id: '1512',
			instructions: [Array],
			name: 'all fours squad stretch',
			secondaryMuscles: [Array],
			target: 'quads',
		},
		{
			bodyPart: 'waist',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/XrCgxHTgPuN-FJ',
			id: '0006',
			instructions: [Array],
			name: 'alternate heel touchers',
			secondaryMuscles: [Array],
			target: 'abs',
		},
		{
			bodyPart: 'back',
			equipment: 'cable',
			gifUrl: 'https://v2.exercisedb.io/image/EXneTJqr5sC7Cj',
			id: '0007',
			instructions: [Array],
			name: 'alternate lateral pulldown',
			secondaryMuscles: [Array],
			target: 'lats',
		},
		{
			bodyPart: 'lower legs',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/6pCUsaWQd0e1su',
			id: '1368',
			instructions: [Array],
			name: 'ankle circles',
			secondaryMuscles: [Array],
			target: 'calves',
		},
		{
			bodyPart: 'back',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/w3Cpu4gISi7CkF',
			id: '3293',
			instructions: [Array],
			name: 'archer pull up',
			secondaryMuscles: [Array],
			target: 'lats',
		},
		{
			bodyPart: 'chest',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/0X63TOxksvu1z2',
			id: '3294',
			instructions: [Array],
			name: 'archer push up',
			secondaryMuscles: [Array],
			target: 'pectorals',
		},
		{
			bodyPart: 'waist',
			equipment: 'body weight',
			gifUrl: 'https://v2.exercisedb.io/image/SZjI7wO-hqHZ19',
			id: '2355',
			instructions: [Array],
			name: 'arm slingers hanging bent knee legs',
			secondaryMuscles: [Array],
			target: 'abs',
		},
	],
];
